### ISSUE TITLE
Import project with template

### ISSUE THREAD

**Issue by Zorin95670** [ditrit/leto-modelizer#132]
## Description

**As a** user, in the homepage,

**I want** select a template and specify the git's url and the model's name

**so that** import the project from git and add the template content inside it.

**Comment by viennem** [comment]
> I want select a template and specify the git's url and the template's name

the user does not specify the template's name after selecting it, it should be the model's name

**Comment by Catepeli** [comment]
What is the project view?
We need to think about the simple navigation first:
The user can just see the template, because he doesn't know this
so first, he can acceed to the project page and maybe check the content of the template,
so he decides to choose this template for his project.

If the template is 'contained' in the library (included in Leto Mod) he doesn't need the git url,

**Comment by Zorin95670** [comment]
Done in #187
